apiVersion: apps/v1
kind: Deployment
metadata:
  name: meuapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meuapp
  template:
    metadata:
      labels:
        app: meuapp
    spec:
      containers:
      - name: meuapp
        image: ofelipedd/meuapp-fastapi:latest
        ports:
        - containerPort: 8000
